# Generated by Django 5.0.6 on 2024-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='desgription',
            field=models.TextField(verbose_name='Desgription of the blog'),
        ),
    ]
