# Generated by Django 5.0.6 on 2024-06-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='Blog_img', verbose_name='Blogun sekli'),
        ),
    ]
