# Generated by Django 5.0.6 on 2024-07-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_publised',
            field=models.BooleanField(default=False),
        ),
    ]
