# Generated by Django 5.0.6 on 2024-07-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogs_is_publised'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar_img', verbose_name='comment avatar'),
            preserve_default=False,
        ),
    ]
