# Generated by Django 5.0.6 on 2024-07-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, default='RentcarLogo.png', null=True, upload_to='avatar_img', verbose_name='Comment avatar'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='coments',
            field=models.TextField(verbose_name='Bloga comment elave et:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name:'),
        ),
    ]
