# Generated by Django 5.0.6 on 2024-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_avatar_alter_comment_coments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, default='RentcarLogo.png', null=True, upload_to='Blog_img', verbose_name='Comment avatar'),
        ),
    ]
