# Generated by Django 5.0.6 on 2024-07-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Blog_img', verbose_name='Comment avatar'),
        ),
    ]
