# Generated by Django 5.0.6 on 2024-08-26 00:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product_version_img')),
                ('title', models.CharField(help_text='Image description', max_length=255, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('cover_image', models.ImageField(upload_to='product_version_img')),
                ('imageHover', models.ImageField(blank=True, help_text='Add hover image for the product version', null=True, upload_to='product_version_img', verbose_name='Hover Image')),
                ('images', models.ManyToManyField(blank=True, related_name='product_versions_img', to='shop.productimage')),
            ],
            options={
                'verbose_name': 'Product Version',
                'verbose_name_plural': 'Product Versions',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='max simvol 100', max_length=100, verbose_name='Name')),
                ('is_new', models.BooleanField(default=False, verbose_name='Is it a new product?')),
                ('price', models.IntegerField(verbose_name='Product Price')),
                ('endirim', models.IntegerField(blank=True, default=None, null=True, verbose_name='Product Discount')),
                ('star', models.DecimalField(decimal_places=1, help_text='minimum (0.0) maximum (10.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Product Rating')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('RewardPoints', models.IntegerField(verbose_name='Reward Points')),
                ('Availability', models.CharField(max_length=200, verbose_name='Product Availability')),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=255, verbose_name='Product Category')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Manufacturer')),
                ('main_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_product', to='shop.productversion', verbose_name='Main Product Version')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_versions', to='shop.shop'),
        ),
    ]
