# Generated by Django 5.0.6 on 2024-08-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Product Price'),
        ),
    ]
