# Generated by Django 5.0.6 on 2024-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_alter_user_options_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
